builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - arm64
      - amd64
    ldflags:
      - -s -w

archives:
  - format: zip
    files:
      - README.md
      - LICENSE
