builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - arm64
      - amd64
    ldflags:
      - -s -w
      - -X github.com/p2pquake/dmdata-jp-api-v2-websocket-client/cmd.Version={{.Version}}
      - -X github.com/p2pquake/dmdata-jp-api-v2-websocket-client/cmd.Commit={{.Commit}}
      - -X github.com/p2pquake/dmdata-jp-api-v2-websocket-client/cmd.Date={{.Date}}

archives:
  - format: zip
    files:
      - README.md
      - LICENSE
